# Generated by Django 4.2.5 on 2025-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clienteprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicoprofile',
            name='purchase_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
