# Generated by Django 4.2.5 on 2025-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mecanicoprofile_purchase_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanicoprofile',
            name='purchase_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
