# Generated by Django 4.2.5 on 2025-04-03 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_clienteprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('concluido', 'Concluído')], default='novo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.fornecedorprofile')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.mecanicoprofile')),
            ],
        ),
    ]
