# Generated by Django 4.2.5 on 2025-04-03 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('users', '0002_alter_clienteprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='users.clienteprofile')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='users.mecanicoprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='vehicles.vehicle')),
            ],
        ),
    ]
